services:
    client:
      build:
        context: .
        dockerfile: ./docker/client/dockerfile
      ports:
        - "2001:80"
      container_name: awp_tool_client
      volumes:
        - ~/docker_test:/usr/share/nginx/html awp_tool
    server:
      build: 
        context: .
        dockerfile: ./docker/server/dockerfile
      container_name: awp_tool_server
      ports:
        - "2000:80"
      volumes:
        - .:/code  
    db:
      image: mysql
      environment:
        MYSQL_DATABASE: awp_tool_db
        MYSQL_USER: wenglerm
        MYSQL_PASSWORD: test
      ports:
        - "2002:80"
      container_name: awp_tool_db
      volumes:
        - ./docker/db/data:/var/lib/mysql